### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by jefferssongalvao** [shprink/wp-api-angular#13]
I tried to install using `sudo npm install wp-api-angular --save` and the error occurred below:

```
> wp-api-angular@3.0.0-alpha7 postinstall /home/jeffersson/desenv/public/sinfo/node_modules/wp-api-angular
> typings install

/home/jeffersson/desenv/public/sinfo/node_modules/configstore/index.js:54
                throw err;
                ^

Error: EACCES: permission denied, open '/home/jeffersson/.config/configstore/typings.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.create.all.get (/home/jeffersson/desenv/public/sinfo/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/home/jeffersson/desenv/public/sinfo/node_modules/configstore/index.js:28:44)
    at Object.<anonymous> (/home/jeffersson/desenv/public/sinfo/node_modules/typings-core/dist/utils/store.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.0 requires a peer of @angular/platform-server@^2.0.0-rc.6 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/common@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular/router-deprecated@2.0.0-rc.1 requires a peer of @angular/platform-browser@2.0.0-rc.1 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/common@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/compiler@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/core@2.0.0-rc.4 but none was installed.
npm WARN ng2-bootstrap@1.0.24 requires a peer of @angular/forms@0.2.0 but none was installed.
npm WARN ng2-page-scroll@1.2.1 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN wp-api-angular@3.0.0-alpha7 requires a peer of @angular/core@2.0.0-rc.2 || 2.0.0-rc.3 || 2.0.0-rc.4 || 2.0.0-rc.5 || 2.0.0-rc.6 || 2.0.0-rc.7 || 2.0.0-rc.8 || 2.0.0-rc.9 but none was installed.
npm WARN wp-api-angular@3.0.0-alpha7 requires a peer of @angular/http@2.0.0-rc.2 || 2.0.0-rc.3 || 2.0.0-rc.4 || 2.0.0-rc.5 || 2.0.0-rc.6 || 2.0.0-rc.7 || 2.0.0-rc.8 || 2.0.0-rc.9 but none was installed.
npm WARN wp-api-angular@3.0.0-alpha7 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN sinfo@0.1.0 No repository field.
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wp-api-angular" "--save"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! wp-api-angular@3.0.0-alpha7 postinstall: 'typings install''
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-api-angular@3.0.0-alpha7 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wp-api-angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wp-api-angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wp-api-angular
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jeffersson/desenv/public/sinfo/npm-debug.log`
```

PS.: Ubuntu 14.04

**Comment by audacitus** [comment]
Having a `Error: EACCES: permission denied` error, can you confirm the issue while running command prompt in **administrator mode**? Running in administrator mode sometimes fixes this kind of issue, but we won't know for sure. Can you try it?

**Comment by shprink** [comment]
Thanks @audacitus for replying! Indeed it seems a user right problem, it is not related to this project IMO.

Here is a fresh install I made:

```
$ npm install wp-api-angular

> wp-api-angular@3.0.0-beta2 postinstall /Users/shprink/Sites/ng2-raffle/node_modules/wp-api-angular
> typings install

typings WARN enoent Path "/Users/shprink/Sites/ng2-raffle/node_modules/wp-api-angular/typings.json" is missing

└── (No dependencies)

ng2-raffle@0.0.0 /Users/shprink/Sites/ng2-raffle
├── UNMET PEER DEPENDENCY @angular/common@2.0.0
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0
├── UNMET PEER DEPENDENCY @angular/core@2.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
└─┬ wp-api-angular@3.0.0-beta2
  └── @angular/http@2.2.0

npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
npm WARN @angular/http@2.2.0 requires a peer of @angular/core@2.2.0 but none was installed.
npm WARN @angular/http@2.2.0 requires a peer of @angular/platform-browser@2.2.0 but none was installed.
```

It works as expected, closing that. Let me know if you still have a problem
