### ISSUE TITLE
npm install fails on:  wp-api-angular@3.0.0-beta2 postinstall: `typings install`

### ISSUE THREAD

**Issue by niggusch** [shprink/wp-api-angular#16]
## Current Setup
Mac OsX Sierra

 $ ng --version
>   angular-cli: 1.0.0-beta.20-4
>  node: 5.10.1
>  os: darwin x64

## Steps to reproduce:

```bash
   $ mkdir wp-api-test
   $ cd wp-api-test
   $ ng init 
   $npm install wp-api-angular
```

##  Console Output

```bash
$ npm install wp-api-angular

> wp-api-angular@3.0.0-beta2 postinstall /Users/nicolas/wp-api-test/node_modules/wp-api-angular
> typings install

sh: typings: command not found
npm WARN @ngtools/webpack@1.1.6 requires a peer of @angular/compiler-cli@2.2.1 but none was installed.
npm WARN @ngtools/webpack@1.1.6 requires a peer of @angular/core@2.2.1 but none was installed.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/nicolas/.nvm/versions/node/v5.10.1/bin/node" "/Users/nicolas/.nvm/versions/node/v5.10.1/bin/npm" "install" "wp-api-angular"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! wp-api-angular@3.0.0-beta2 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the wp-api-angular@3.0.0-beta2 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wp-api-angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wp-api-angular
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wp-api-angular
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nicolas/wp-api-test/npm-debug.log
```

# Output of npm-debug.log 

```
161 silly install wp-api-angular@3.0.0-beta2 /Users/nicolas/wp-api-test/node_modules/.staging/wp-api-angular-ac82b28e
162 info lifecycle wp-api-angular@3.0.0-beta2~install: wp-api-angular@3.0.0-beta2
163 silly lifecycle wp-api-angular@3.0.0-beta2~install: no script for install, continuing
164 silly doSerial postinstall 1
165 silly postinstall wp-api-angular@3.0.0-beta2 /Users/nicolas/wp-api-test/node_modules/.staging/wp-api-angular-ac82b28e
166 info lifecycle wp-api-angular@3.0.0-beta2~postinstall: wp-api-angular@3.0.0-beta2
167 verbose lifecycle wp-api-angular@3.0.0-beta2~postinstall: unsafe-perm in lifecycle true
168 verbose lifecycle wp-api-angular@3.0.0-beta2~postinstall: PATH: /Users/nicolas/.nvm/versions/node/v5.10.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/nicolas/wp-api-test/node_modules/wp-api-angular/node_modules/.bin:/Users/nicolas/wp-api-test/node_modules/.bin:/Users/nicolas/.nvm/versions/node/v5.10.1/bin:/usr/local/sbin:/Users/nicolas/.nvm/versions/node/v5.10.1/bin:/usr/local/bin:/Users/nicolas/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/myApp:/opt/X11/bin:/opt/smartrsa/tools/usr/local/bin:/opt/jboss/jboss/bin
169 verbose lifecycle wp-api-angular@3.0.0-beta2~postinstall: CWD: /Users/nicolas/wp-api-test/node_modules/wp-api-angular
170 silly lifecycle wp-api-angular@3.0.0-beta2~postinstall: Args: [ '-c', 'typings install' ]
171 info lifecycle wp-api-angular@3.0.0-beta2~postinstall: Failed to exec postinstall script
172 verbose unlock done using /Users/nicolas/.npm/_locks/staging-bafef9d47d515e20.lock for /Users/nicolas/wp-api-test/node_modules/.staging
173 silly rollbackFailedOptional Starting
174 silly rollbackFailedOptional Finishing
175 silly runTopLevelLifecycles Starting
176 silly runTopLevelLifecycles Finishing
177 silly install printInstalled
178 warn @ngtools/webpack@1.1.6 requires a peer of @angular/compiler-cli@2.2.1 but none was installed.
179 warn @ngtools/webpack@1.1.6 requires a peer of @angular/core@2.2.1 but none was installed.
180 verbose stack Error: wp-api-angular@3.0.0-beta2 postinstall: `typings install`
180 verbose stack spawn ENOENT
180 verbose stack     at ChildProcess.<anonymous> (/Users/nicolas/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/utils/spawn.js:17:16)
180 verbose stack     at emitTwo (events.js:100:13)
180 verbose stack     at ChildProcess.emit (events.js:185:7)
180 verbose stack     at maybeClose (internal/child_process.js:850:16)
180 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
181 verbose pkgid wp-api-angular@3.0.0-beta2
182 verbose cwd /Users/nicolas/wp-api-test
183 error Darwin 16.1.0
184 error argv "/Users/nicolas/.nvm/versions/node/v5.10.1/bin/node" "/Users/nicolas/.nvm/versions/node/v5.10.1/bin/npm" "install" "wp-api-angular"
185 error node v5.10.1
186 error npm  v3.8.3
187 error file sh
188 error code ELIFECYCLE
189 error errno ENOENT
190 error syscall spawn
191 error wp-api-angular@3.0.0-beta2 postinstall: `typings install`
191 error spawn ENOENT
192 error Failed at the wp-api-angular@3.0.0-beta2 postinstall script 'typings install'.
192 error Make sure you have the latest version of node.js and npm installed.
192 error If you do, this is most likely a problem with the wp-api-angular package,
192 error not with npm itself.
192 error Tell the author that this fails on your system:
192 error     typings install
192 error You can get information on how to open an issue for this project with:
192 error     npm bugs wp-api-angular
192 error Or if that isn't available, you can get their info via:
192 error     npm owner ls wp-api-angular
192 error There is likely additional logging output above.
193 verbose exit [ 1, true ]
```

**Comment by shprink** [comment]
Thanks for sharing this.

`typings` is not installed locally you are right. 

Run this for now and try again `npm i typings -g`

I will add `typings` as a local dependency, same as [here](https://github.com/angular/angularfire2/blob/master/package.json#L81). PR welcome

**Comment by niggusch** [comment]
:thumbsup: Thanks, this helped!

**Comment by shprink** [comment]
typings is not required to be installed globally. Following AngularFIre here.
